services:
  vidspark:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      INCLUDE_PROXY_FALLBACK: "0"
      PROXY_ENABLED: "0"
    ports:
      - "7002:7002"
    restart: unless-stopped
